<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>JHYY.SetUC</RootNamespace>
    <AssemblyName>jhyy-setuc</AssemblyName>
    <Nullable>disable</Nullable>
    <UseWindowsForms>false</UseWindowsForms>
  </PropertyGroup>
</Project>